# Generated by Django 3.0.7 on 2020-12-16 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Room',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerA', models.CharField(max_length=15)),
                ('playerB', models.CharField(max_length=15)),
                ('join_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.Room')),
            ],
            options={
                'verbose_name_plural': 'Player',
            },
        ),
    ]
