# Generated by Django 3.0.7 on 2020-12-16 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='playerA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerA', models.CharField(max_length=15)),
                ('join_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.Room')),
            ],
            options={
                'verbose_name_plural': 'PlayerA',
            },
        ),
        migrations.CreateModel(
            name='playerB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerB', models.CharField(max_length=15)),
                ('join_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.Room')),
            ],
            options={
                'verbose_name_plural': 'PlayerB',
            },
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
