# Generated by Django 3.0.7 on 2020-12-16 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0002_auto_20201216_2059'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='playerB',
            new_name='player',
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name_plural': 'Player'},
        ),
        migrations.RenameField(
            model_name='player',
            old_name='playerB',
            new_name='player',
        ),
        migrations.DeleteModel(
            name='playerA',
        ),
    ]
