# Generated by Django 3.0.7 on 2020-12-16 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0003_auto_20201216_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='player',
            new_name='player_name',
        ),
    ]
