# Generated by Django 3.0.7 on 2020-12-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0005_auto_20201216_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='points_decided',
            field=models.IntegerField(default=10),
        ),
    ]
