# Generated by Django 3.0.7 on 2020-12-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0006_player_points_decided'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='creater',
            field=models.BooleanField(default=True),
        ),
    ]
