# Generated by Django 3.0.7 on 2020-12-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0007_player_creater'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='rps_choice',
            field=models.CharField(default=None, max_length=8),
        ),
    ]
