# Generated by Django 3.0.7 on 2020-12-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0008_player_rps_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='rps_choice',
            field=models.CharField(default=0, max_length=8),
        ),
    ]
