# Generated by Django 3.0.7 on 2020-12-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0009_auto_20201218_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='rps_choice',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
